services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: askwise
      POSTGRES_PASSWORD: askwisepass
      POSTGRES_DB: askwise_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
